version: '3.7'

services:

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      #- 7473:7473 HTTPS
      - 7687:7687
    environment: #To remove password requirement 
      NEO4J_AUTH: neo4j/test
