version: '3.7'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    container_name: tag-match-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      #- 7473:7473 HTTPS
      - 7687:7687
    environment: #To remove password requirement 
      NEO4J_AUTH: neo4j/test
    container_name: tag-match-neo
