# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.11.245.32:5000/silicon-pattern-251401/tag-match
  tag: 0.0.15
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:
  MONGO_URL: mongodb.staging.tag-match.com
  MONGO_AUTH_DB: auth
  NEO4J_URL: neo4j.staging.tag-match.com

envSecretsUsernames:
  MONGO_AUTH_USERNAME: mongo-auth
  NEO4J_USERNAME: neo-user

envSecretsPasswords:
  MONGO_AUTH_PASSWORD: mongo-auth
  NEO4J_PASSWORD: neo-user

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: tag-match
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /up
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 2
readinessProbe:
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 2
